# Numpy Project :- Student Result Analysis

##### **Description About Data**
There is a 'students_marks.csv' file which contains data of 100 students.
There are 100 rows where every row representing a student data. 
There are four columns where first column contains roll number and 
next three columns contains marks of first, second and third subject respectively.

**Import the numpy library**

In [1]:
import numpy as np

**Read the data from csv file into numpy array**

In [2]:
students_data = np.loadtxt('students_marks.csv', delimiter=',')

**Find the shape of data**

In [3]:
students_data.shape

(100, 4)

**Display first 5 rows of data**

In [5]:
print(students_data[:5])

[[101.  81.  75.  68.]
 [102.  42.  55.  49.]
 [103.  90.  88.  92.]
 [104.  67.  71.  65.]
 [105.  33.  40.  37.]]


**Find the total of marks of each student**

In [13]:
total_marks = students_data[:,1:].sum(axis=1)
print(total_marks[:5])

[224. 146. 270. 203. 110.]


**Add a new column that will store the total of marks of each student**

In [14]:
print(total_marks.reshape(1, -1)[:,:5])

[[224. 146. 270. 203. 110.]]


In [15]:
print(total_marks.reshape(-1, 1)[:5])

[[224.]
 [146.]
 [270.]
 [203.]
 [110.]]


In [16]:
print(total_marks[:5])

[224. 146. 270. 203. 110.]


In [17]:
total_marks = total_marks.reshape(-1, 1)

In [18]:
print(total_marks[:5])

[[224.]
 [146.]
 [270.]
 [203.]
 [110.]]


In [19]:
students_data = np.concatenate((students_data, total_marks), axis=1)

**Display first 5 rows of data with newly added column for total of marks**

In [20]:
print(students_data[:5])

[[101.  81.  75.  68. 224.]
 [102.  42.  55.  49. 146.]
 [103.  90.  88.  92. 270.]
 [104.  67.  71.  65. 203.]
 [105.  33.  40.  37. 110.]]


**Find the average of marks of each student**

In [21]:
average_marks = students_data[:,-1] / 3
print(average_marks[:5])

[74.66666667 48.66666667 90.         67.66666667 36.66666667]


**Add a new column that will store the average of marks of each student**

In [22]:
average_marks = average_marks.reshape(-1, 1)
print(average_marks[:5])

[[74.66666667]
 [48.66666667]
 [90.        ]
 [67.66666667]
 [36.66666667]]


In [23]:
students_data = np.concatenate((students_data, average_marks), axis=1)

**Display first 5 rows of data with newly added column for average of marks**

In [24]:
print(students_data[:5])

[[101.          81.          75.          68.         224.
   74.66666667]
 [102.          42.          55.          49.         146.
   48.66666667]
 [103.          90.          88.          92.         270.
   90.        ]
 [104.          67.          71.          65.         203.
   67.66666667]
 [105.          33.          40.          37.         110.
   36.66666667]]


**Find the average of marks of first subject**

In [26]:
print(f"Average Marks of first subject: {students_data[:,1].mean()}")

Average Marks of first subject: 70.42


**Find the average of marks of second subject**

In [27]:
print(f"Average Marks of second subject: {students_data[:,2].mean()}")

Average Marks of second subject: 71.42


**Find the average of marks of third subject**

In [ ]:
print(f"Average Marks of third subject: {students_data[:,3].mean()}")

**Find the highest marks in first subject**

In [28]:
print(f"Highest marks of first subject: {students_data[:,1].max()}")

Highest marks of first subject: 99.0


**Find the highest marks in second subject**

In [29]:
print(f"Highest marks of second subject: {students_data[:,2].max()}")

Highest marks of second subject: 100.0


**Find the highest marks in third subject**

In [30]:
print(f"Highest marks of third subject: {students_data[:,3].max()}")

Highest marks of third subject: 99.0


**Find the lowest marks in first subject**

In [31]:
print(f"Highest marks of first subject: {students_data[:,1].min()}")

Highest marks of first subject: 33.0


**Find the lowest marks in second subject**

In [32]:
print(f"Highest marks of second subject: {students_data[:,2].min()}")

Highest marks of second subject: 40.0


**Find the lowest marks in third subject**

In [33]:
print(f"Highest marks of third subject: {students_data[:,3].min()}")

Highest marks of third subject: 36.0


**Count how many number of students have scored more than or equal to 90 marks in first subject**

In [36]:
print(f"Number of Students scored more than or equal to 90 in first subject: {
(students_data[:,1] >= 90).sum()}")

Number of Students scored more than or equal to 90 in first subject: 20


**Count how many number of students have scored more than or equal to 90 marks in second subject**

In [37]:
print(f"Number of Students scored more than or equal to 90 in second subject: {
(students_data[:,2] >= 90).sum()}")

Number of Students scored more than or equal to 90 in second subject: 13


**Count how many number of students have scored more than or equal to 90 marks in third subject**

In [38]:
print(f"Number of Students scored more than or equal to 90 in third subject: {
(students_data[:,3] >= 90).sum()}")

Number of Students scored more than or equal to 90 in third subject: 20


**Count how many number of students have scored average marks more than or equal to 75**

In [40]:
print(f"Number of Students scored average marks more than or equal to 75: {
(students_data[:,-1] >= 75).sum()}")

Number of Students scored average marks more than or equal to 75: 45


**Count the number of students who have scored average marks less than 50**

In [41]:
print(f"Number of Students scored average marks less than 50: {
(students_data[:,-1] < 50).sum()}")

Number of Students scored average marks less than 50: 17


**Count the number of students who have scored average marks between 80 and 90**

In [42]:
print(f"Number of Students scored average marks between 80 and 90: {
((students_data[:,-1] >= 80) & (students_data[:,-1] >= 90)).sum()}")

Number of Students scored average marks between 80 and 90: 18


**Find the students data who have scored marks more than or equal to 90 in all subjects**

In [43]:
all_subjects_90 = students_data[(students_data[:,1] >= 90) & 
(students_data[:,2] >= 90) & (students_data[:,3] >= 90)]
print(all_subjects_90)

[[108.          95.          91.          97.         283.
   94.33333333]
 [114.          99.         100.          98.         297.
   99.        ]
 [123.          97.          93.          96.         286.
   95.33333333]
 [133.          94.          90.          95.         279.
   93.        ]
 [138.          98.          95.          99.         292.
   97.33333333]
 [149.          96.          94.          97.         287.
   95.66666667]
 [160.          95.          91.          94.         280.
   93.33333333]
 [164.          99.          97.          98.         294.
   98.        ]
 [175.          97.          93.          96.         286.
   95.33333333]
 [180.          94.          90.          93.         277.
   92.33333333]
 [188.          98.          95.          99.         292.
   97.33333333]
 [197.          96.          92.          95.         283.
   94.33333333]]


**Count how many number of students have scored marks more than or equal to 90 in all subjects**

In [47]:
print(f"Number of Students scored marks more than or equal to 90 in all subject: {
all_subjects_90.shape[0]}")

Number of Students scored marks more than or equal to 90 in all subject: 12


**Find the students data who have scored marks more than or equal to 90 in any subject**

In [48]:
any_subject_90 = students_data[(students_data[:,1] >= 90) | 
(students_data[:,2] >= 90) | (students_data[:,3] >= 90)]
print(any_subject_90)

[[103.          90.          88.          92.         270.
   90.        ]
 [108.          95.          91.          97.         283.
   94.33333333]
 [110.          88.          85.          90.         263.
   87.66666667]
 [114.          99.         100.          98.         297.
   99.        ]
 [118.          92.          89.          94.         275.
   91.66666667]
 [123.          97.          93.          96.         286.
   95.33333333]
 [128.          91.          86.          93.         270.
   90.        ]
 [133.          94.          90.          95.         279.
   93.        ]
 [138.          98.          95.          99.         292.
   97.33333333]
 [141.          89.          92.          88.         269.
   89.66666667]
 [144.          93.          89.          91.         273.
   91.        ]
 [149.          96.          94.          97.         287.
   95.66666667]
 [154.          90.          87.          91.         268.
   89.33333333]
 [160.          95.      

**Count how many number of students have scored marks more than or equal to 90 in any subject**

In [49]:
print(f"Number of Students scored marks more than or equal to 90 in any subject: {
any_subject_90.shape[0]}")

Number of Students scored marks more than or equal to 90 in any subject: 22


**Save the students data who have scored marks more than or equal to 90 in all subjects to 'all_subjets_90' csv file**

In [51]:
np.savetxt("all_subjects_90.csv", all_subjects_90, delimiter=",", 
header="Roll Number,Marks 1,Marks 2,Marks 3,Total Marks,Average Marks",
fmt=["%d","%d","%d","%d","%d","%.2f"], comments="")
print("Data is saved successfully")

Data is saved successfully


**Save the students data who have scored marks more than or equal to 90 in any subject to 'any_subjet_90' csv file**

In [52]:
np.savetxt("any_subject_90.csv", any_subject_90, delimiter=",", 
header="Roll Number,Marks 1,Marks 2,Marks 3,Total Marks,Average Marks",
fmt=["%d","%d","%d","%d","%d","%.2f"], comments="")
print("Data is saved successfully")

Data is saved successfully


**Save the Students Data and Calculated Total and Average Marks to 'students_result' csv file**

In [53]:
np.savetxt("students_result.csv", students_data, delimiter=",", 
header="Roll Number,Marks 1,Marks 2,Marks 3,Total Marks,Average Marks",
fmt=["%d","%d","%d","%d","%d","%.2f"], comments="")
print("Data is saved successfully")

Data is saved successfully
